### ISSUE TITLE
work with binary file

### ISSUE THREAD

**Issue by ghost** [Mikrozone-Server/rw-i2c#2]
Add a binary file format for "read from" or "write to file".

**Comment by pefabian** [comment]
@mikrozone Binary mode of original write-EDID is hardcoded (xxd is used to convert binary stream to hex) 
Is the functionality broken?

for reading i2cdump is used directly to file. I guess that dumps hex; I can use xxd -r to convert to bin if needed.

**Comment by EdizonTN** [comment]
This script will be used not for EDID read/write. It will be for reading/writing of ANY I2C device. Due this, binary file is better.

**Comment by pefabian** [comment]
@EdizonTN original script (from write-EDID repo) has Hex mode and Binary mode, in this implementation, I used the Binary mode. Is it not working for write mode?

**Comment by EdizonTN** [comment]
Read from file is OK. But write to file is in the HEX mode not in binary.

**Comment by pefabian** [comment]
Ok, I see. 
The naming convention relates to I2C not file, i.e. Write is from file to I2C (set), Read is from I2C to file (dump).

I will mod the script to put dump as binary.
